GOOGLE_BROWSER_API_KEY: AIzaSyDBFwnE80k5x7uhKdAulSMwX7FQ-jdp7Pc
GOOGLE_OAUTH2_ID: "574991190872-6r0hg4jv7i9varh3fra711g06krqv4vn.apps.googleusercontent.com"    
GOOGLE_OAUTH2_SECRET: "j6_WnJ1VWSXcQocQbH9S0X4v"
APPLICATION_NAME: "Church Mapper"
APPLICATION_VERSION: "0.1"
SESSION_LENGTH_IN_HOURS: "24"
ENCRYPTION_KEY: "aselki52kbl0pl4bwzmnhpuggotwlkmkl6r"
FACEBOOK_KEY: "1000996849953901"
FACEBOOK_SECRET: "345ebd57729664cf6e98c7c88c5dbfca"
MICROSOFT_LIVE_KEY: "704e5906-4a51-40cf-bf9b-e2fe06d585f1"
MICROSOFT_LIVE_SECRET: "cthmCkR235k4VopueZxZusr"
OAUTH_CALLBACK_HOST: "http://localhost:3000"
AWS_ID_KEY: "amzn1.application-oa2-client.2273cca939aa4a759544db3e681fac3a"
AWS_ID_SECRET: "4bdbf9fd9eaa7fed210e572e7ad7a5eabf9619358c76596c0228459078ab03cf"
HTTPS_ROOT: "http://localhost:3000"

